views/views.py
import requests
from flask import (
    render_template,
    flash,
    Blueprint,
    redirect,
    request,
    url_for,
    current_app,
)
from flask_login import login_user, login_required, logout_user, current_user

from views.forms import RegistrationForm, LoginForm, BalanceForm
from models import Balance
from service import login_manager, CustomUser


blueprint = Blueprint('blueprint', __name__)


@login_manager.user_loader
def load_user(user_url):
    """
    This function is used by Flask-Login to load the current user object from the user ID that
    is stored in the session. This function takes a user URL as an argument and returns a
    CustomUser object that is created by calling the create_from_api class method of the
    CustomUser class.

    Args:
    user_url(str): The URL of the current user.

    Returns:
    CustomUser: A CustomUser object representing the current user.
    """
    return CustomUser.create_from_api(user_url)


@blueprint.route('/', methods=['GET', 'POST'])
def home():
    """
    Function that renders the home page of the application.

    If the user is authenticated, this function retrieves the balances of the user
    from the API, according to the dates selected by the user in the search form.
    The balances are displayed in a table in the template.

    Returns:
        A rendered template ('home.html') with the following context variables:
            - from_date: A string with the 'from' date selected by the user.
            - to_date: A string with the 'to' date selected by the user.
            - balances: A list of dictionaries with the balances of the user.

        Each dictionary contains the following keys:
            * coin_abbreviation: A string with the abbreviation of the coin.
            * amount: A float with the amount of the coin in the balance.
            * value: A float with the value of the coin in the balance, in USD.

    """
    current_app.logger.info("VIEW - Request from user - home page")
    from_date = request.form.get('from-date')
    to_date = request.form.get('to-date')
    context = {
        "from_date": from_date,
        "to_date": to_date,
    }
    current_app.logger.info(f"VIEW - Filters {context}")
    if current_user.is_authenticated:
        current_app.logger.info("VIEW - Balance search start")
        response = requests.get(
            timeout=5,
            url=f'{request.url_root}api/v1/balances/{current_user.id}',
            json={
                "from_date": from_date,
                "to_date": to_date,
            }
        )
        if response.status_code == 200:
            context['balances'] = response.json()
            current_app.logger.info(f"VIEW - Balances found: '{len(context['balances'])}'")
        current_app.logger.info("VIEW - Balance search end")
    return render_template('home.html', context=context)


@blueprint.route('/add-balance', methods=['GET', 'POST'])
@login_required
def add_balance():
    """
    Function that renders a form for user to add balance for a specific coin(crypto).

    Returns:
        If form submission is valid and API response status code is 201, then redirects to home page
        Otherwise, re-renders the same form with error message.

    """
    form = BalanceForm()

    coins = requests.get(url=f'{request.url_root}api/v1/coins', timeout=5)

    if coins.status_code == 200:
        available_coins = [
            (coin['id'], coin['abbreviation'])
            for coin in coins.json()
        ]
        form.coin.choices = available_coins

    if form.validate_on_submit():
        current_app.logger.info("VIEW - Add Balance request started")
        response = requests.post(
            timeout=5,
            url=f'{request.url_root}api/v1/balances',
            json={
                'user_id': current_user.id,
                'coin_id': int(form.coin.data),
                'amount': str(form.amount.data)
            }
        )
        if response.status_code == 201:
            flash('Coin Added Successfully!')
            current_app.logger.info("VIEW - Add Balance successful")
            current_app.logger.info("VIEW - Add Balance request ended")
            return redirect(url_for('blueprint.home'))
        current_app.logger.info("VIEW - Add Balance request failed")
        flash('Something went wrong, please try again!')
    return render_template('balance.html', form=form)


@blueprint.route('/edit-balance/<int:balance_id>', methods=['GET', 'POST', 'PUT'])
@login_required
def edit_balance(balance_id):
    """
    Function that renders the edit balance page and allows users to
    update their balance information.

    Args:
        balance_id: integer representing the id of the balance to be edited.

    Returns:
        If the balance is successfully updated, the function redirects
        the user to the home page with a success message.

        If there's an error, the function redirects
        the user to the edit balance page with an error message.
    """
    form = BalanceForm()
    balance = Balance.query.get(balance_id)
    coins = requests.get(url=f'{request.url_root}api/v1/coins', timeout=5)

    if coins.status_code == 200:
        available_coins = [
            (coin['id'], coin['abbreviation'])
            for coin in coins.json()
        ]
        form.coin.choices = available_coins

    if form.validate_on_submit():
        current_app.logger.info("VIEW - Edit Balance request started")
        response = requests.put(
            timeout=5,
            url=f'{request.url_root}api/v1/balances/{balance_id}',
            json={
                'coin_id': int(form.coin.data),
                'amount': str(form.amount.data)
            }
        )
        if response.status_code == 201:
            flash('Balance Updated Successfully!')
            current_app.logger.info(f"VIEW - Edit Balance with"
                                    f" id '{balance.id}' - updated successfully")
            current_app.logger.info("VIEW - Edit Balance request ended")
            return redirect(url_for('blueprint.home'))
        current_app.logger.info("VIEW - Edit Balance request failed")
        flash('Sorry, something went wrong :( Try again...')
    form.coin.data = balance.coin_id
    form.amount.data = balance.amount
    return render_template('edit_balance.html', form=form, balance=balance)


@blueprint.route('/delete-balance/<int:balance_id>', methods=['GET', 'POST'])
@login_required
def delete_balance(balance_id: int):
    """
    Function that handles deleting a balance for a logged-in user.

    Args:
        balance_id(int): The ID of the balance to be deleted.

    Returns:
        redirect: Redirects to the home page after the balance has been deleted.
    """
    response = requests.delete(
        timeout=5,
        url=f'{request.url_root}api/v1/balances/{balance_id}'
    )
    if response.status_code == 204:
        current_app.logger.info("VIEW - Balance delete successful")
        flash("Balance deleted")

    return redirect(url_for('blueprint.home'))


@blueprint.route('/register', methods=['GET', 'POST'])
def register():
    """
    Function that renders a register page for users to register
    into the application.
    If the user submits valid credentials, they are registered,
    logged in and redirected to the home page.

    If the credentials are invalid, an error message is displayed
    and the login page is re-rendered.

    Returns:
        If the request method is GET, returns a rendered register
        template with a sign-up form.
        If the request method is POST and the form is valid, registers,
        logs in the user and redirects them to the home page.
        If the request method is POST and the form is invalid, returns
        a rendered register template with error messages.
    """
    form = RegistrationForm()
    email = form.email.data
    if form.validate_on_submit():
        current_app.logger.info("VIEW - Register request started")
        response = requests.post(
            timeout=5,
            url=f'{request.url_root}api/v1/users',
            json={'email': form.email.data, 'password': form.password.data}
        )
        if response.status_code in [200, 201]:
            flash('User Registered Successfully!')
            login_user(CustomUser.create_from_api(response.headers.get('Location')))
            current_app.logger.info(f"VIEW - User with "
                                    f"id '{current_user.id}' - registered successfully")
            current_app.logger.info("VIEW - Register request ended")
            return redirect(url_for('blueprint.home'))
        current_app.logger.info("VIEW - Register request failed")
        flash('Something went wrong!')
    return render_template('register.html', form=form, email=email)


@blueprint.route('/login', methods=['GET', 'POST'])
def login():
    """
    Function that renders a login page for users to logs-in
    into the application.
    If the user submits valid credentials, they are logged in
    and redirected to the home page.
    If the credentials are invalid, an error message is displayed
    and the login page is re-rendered.

    Returns:
        If the request method is GET, returns a rendered login
         template with a login form.
        If the request method is POST and the form is valid,
         logs in the user and redirects them to the home page.
        If the request method is POST and the form is invalid,
         returns a rendered login template with error messages.
    """
    form = LoginForm()
    if form.validate_on_submit():
        current_app.logger.info("VIEW - Login request started")
        response = requests.post(
            timeout=5,
            url=f'{request.url_root}api/v1/users',
            json={'email': form.email.data, 'password': form.password.data}
        )
        if response.status_code == 200:
            flash('User Logged Successfully!')

templates/balance.html
{% extends 'base.html' %}

{% block body %}
    <div class="shadow p-5 mb-5 bg-body rounded">
        <div class="text-center adjustment-bottom"><h2>Add Balance Page</h2></div>
            <form method="POST">
                {{ form.hidden_tag() }}
                <div class="mb-3">
                    {{ form.coin.label(class="form-label") }}
                    {{ form.coin(class="form-control") }}
                    {% for error in form.coin.errors %}
                        <span style="color: red;">{{ error }}</span><br>
                    {% endfor %}
                </div>
                <div class="mb-3">
                    {{ form.amount.label(class="form-label") }}
                    {{ form.amount(size=30, class="form-control") }}
                    {% for error in form.amount.errors %}
                        <span style="color: red;">{{ error }}</span><br>
                    {% endfor %}
                </div>

                {{ form.submit(class="btn btn-outline-primary") }}
            </form>
    </div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <link rel="stylesheet" href="../static/styles/styles.css">
    <title>{% block title %}CRYPTEX{% endblock %}</title>

</head>
<body>

<div class="container">
{% include 'sidebar.html' %}
<div class="main">
    <div class="row">
        <div class="col-12">
            <h1 class="mt-2 text-center">CRYPTEX</h1>
            <hr class="mt-0 mb-4">

            {% for message in get_flashed_messages() %}
                <div class="alert alert-success alert-dismissible fade show" role="alert">
                <strong>Holy guacamole!</strong> {{ message }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
             </div>
            {% endfor %}

            {% block body %}
            {% endblock %}
        </div>
    </div>
</div>

</div>


<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.min.js" integrity="sha384-mQ93GR66B00ZXjt0YO5KlohRA5SY2XofN4zfuZxLkoj1gXtW8ANNCe9d5Y3eG5eD" crossorigin="anonymous"></script>
</body>
</html>

templates/edit_balance.html
{% extends 'base.html' %}

{% block body %}
    <div class="shadow p-5 mb-5 bg-body rounded">
        <div class="text-center adjustment-bottom"><h2>Edit Balance Page</h2></div>
            <form method="POST" action="{{ url_for('blueprint.edit_balance', balance_id=balance.id) }}">
                {{ form.hidden_tag() }}
                <div class="mb-3">
                    {{ form.coin.label(class="form-label") }}
                    {{ form.coin(class="form-control") }}
                    {% for error in form.coin.errors %}
                        <span style="color: red;">{{ error }}</span><br>
                    {% endfor %}
                </div>
                <div class="mb-3">
                    {{ form.amount.label(class="form-label") }}
                    {{ form.amount(size=30, class="form-control") }}
                    {% for error in form.amount.errors %}
                        <span style="color: red;">{{ error }}</span><br>
                    {% endfor %}
                </div>
                <a class="btn btn-outline-secondary" href="{{ url_for('blueprint.home')}}">Cancel</a>
                {{ form.submit(class="btn btn-outline-success", value="Save") }}
            </form>
    </div>
{% endblock %}

templates/home.html
{% extends 'base.html' %}

{% block body %}
    {% if current_user.is_authenticated %}
        <form class="adjustment-bottom" method="POST" action="{{ url_for('blueprint.home') }}">
            <div class="row">
                <div class="col-sm-5 mb-2">
                    <input class="form-control me-2" type="date" id="from-date" name="from-date" value="{{ context.from_date }}" aria-label="From">
                </div>
                <div class="col-sm-5 mb-2">
                    <input class="form-control me-2" type="date" id="to-date" name="to-date" value="{{ context.to_date }}" aria-label="To">
                </div>
                 <div class="col-lg-2 mb-2">
                    <button class="btn btn-outline-success" style="width: 100%" type="submit">Search</button>
                </div>
            </div>
        </form>
    {% endif %}
    <div class="shadow p-5 mb-5 bg-body-tertiary rounded ">
        <div class="text-center adjustment-bottom fst-italic">
            <h2>Home Page</h2>
        </div>
        {% if current_user.is_authenticated %}
            {% if context.balances %}
                <div class="row ">
                    {% for balance in context.balances %}
                        <div class="col-lg-4 card-style">
                            <div class="border border-secondary rounded card-content shadow p-3 mb-5">
                                <h2>{{ balance.coin }}</h2>
                                <div>
                                    Amount: {{ balance.amount }}
                                </div>
                                <div>
                                    Value: {{ balance.value }}
                                </div>
                                <br>
                                <a class="btn btn-outline-secondary" href="{{ url_for('blueprint.edit_balance', balance_id=balance.id)}}">Edit</a>
                                <a class="btn btn-outline-danger" href="{{ url_for('blueprint.delete_balance', balance_id=balance.id)}}">Delete</a>
                            </div>

                        </div>
                    {% endfor %}
                </div>
            {% else %}
                <h1>Let's add our first balance <a class="link-success" href="{{ url_for('blueprint.add_balance')}}">$$$</a></h1>
            {% endif %}
        {% else %}
            <h1><a href="{{ url_for('blueprint.login')}}">Join</a> US :)</h1>
        {% endif %}
    </div>
{% endblock %}

templates/login.html
{% extends 'base.html' %}

{% block body %}
    <div class="shadow p-5 mb-5 bg-body rounded">
        <div class="text-center adjustment-bottom"><h2>Login Page</h2></div>
            <form method="POST">
                {{ form.hidden_tag() }}
                <div class="mb-3">
                    {{ form.email.label(class="form-label") }}
                    {{ form.email(size=30, class="form-control") }}
                    {% for error in form.email.errors %}
                        <span style="color: red;">{{ error }}</span><br>
                    {% endfor %}
                </div>
                <div class="mb-3">
                    {{ form.password.label(class="form-label") }}
                    {{ form.password(size=30, class="form-control") }}
                    {% for error in form.password.errors %}
                        <span style="color: red;">{{ error }}</span><br>
                    {% endfor %}
                </div>
                {{ form.submit(class="btn btn-outline-dark") }}
            </form>
            <br>
            Not a member? <a class="link-primary" href="{{ url_for('blueprint.register')}}">Register here</a>
    </div>
{% endblock %}

templates/register.html
{% extends 'base.html' %}

{% block body %}
    <div class="shadow p-5 mb-5 bg-body rounded">
        <div class="text-center adjustment-bottom"><h2>Sign Up Page</h2></div>
            <form method="POST">
                {{ form.hidden_tag() }}
                <div class="mb-3">
                    {{ form.email.label(class="form-label") }}
                    {{ form.email(size=30, class="form-control") }}
                    {% for error in form.email.errors %}
                        <span style="color: red;">{{ error }}</span><br>
                    {% endfor %}
                </div>
                <div class="mb-3">
                    {{ form.password.label(class="form-label") }}
                    {{ form.password(class="form-control") }}
                    {% for error in form.password.errors %}
                        <span style="color: red;">{{ error }}</span><br>
                    {% endfor %}
                </div>
               <div class="mb-3">
                    {{ form.confirm_password.label(class="form-label") }}
                    {{ form.confirm_password(class="form-control") }}
                    {% for error in form.confirm_password.errors %}
                        <span style="color: red;">{{ error }}</span><br>
                    {% endfor %}
               </div>
                {{ form.submit(class="btn btn-outline-dark") }}
            </form>
            <br>
            Already a member? <a href="{{ url_for('blueprint.login')}}">Login here</a>
{#        <br><br>#}
{#        <table class="table table-hover table-striped">#}
{#            {% for user_list in users %}#}
{#                <tr>#}
{#                    <td>#}
{#                        {{ user_list.id }}. {{ user_list.email }} - PW: {{ user_list.password }}#}
{#                    </td>#}
{#                </tr>#}
{#            {% endfor %}#}
{#        </table>#}
    </div>
{% endblock %}

templates/sidebar.html
<div class="sidenav fst-italic">
    <a href="{{ url_for('blueprint.home')}}" class="animation-text">Home</a>
    {% if current_user.is_authenticated %}
        <a href="{{ url_for('blueprint.add_balance')}}" class="animation-text">Add Coin</a>
        <a href="{{ url_for('blueprint.logout')}}" class="animation-text">Logout</a>
    {% else %}
        <a href="{{ url_for('blueprint.login')}}" class="animation-text">Login</a>
    {% endif %}
    <div class="credentials fst-italic">
        <p>Sheredko Limited</p>
    </div>
</div>